name: Build and Push

on:
  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - master

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: CGO_ENABLED=0 go build -o dist/uwsgi-exporter-linux-amd64
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
